### ISSUE TITLE
Email not received 

### ISSUE THREAD

**Issue by lorenzo-camaione** [DavideDiCarlo/Twistory2.0#17]
Tried to sign in I don't receive the confirmations email.
Greetings, Lorenzo.

**Comment by DavideDiCarlo** [comment]
Hi Lorenzo,
Are you running the app in development or production mode?

**Comment by lorenzo-camaione** [comment]
No, I've gone to "www.ragazzidel99.it".

**Comment by vdinicola** [comment]
Cannot reproduce. I tested it and received the registration email correctly (see screenshot). Registration completion link worked as well.
Please check whether the confirmation email went to your Spam folder.

Closing the bug.
![no-repro-bug](https://cloud.githubusercontent.com/assets/2458919/7286397/ee7d4b00-e94b-11e4-89ec-ea96d34d9f8e.png)
