### ISSUE TITLE
P2 - Missing bx_loader.gif

### ISSUE THREAD

**Issue by vdinicola** [DavideDiCarlo/Twistory2.0#19]
When loading the index page, the production.log shows an error (copied below).
Very likely, the code refers to a "bx_loader.gif" file that does not exist. Please either remove the reference to that file or add it to the codebase.

=========================================

I, [2015-04-24T11:07:39.116574 #14660]  INFO -- : Started GET "/" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.120314 #14660]  INFO -- : Processing by HomeController#index as HTML
I, [2015-04-24T11:07:39.127331 #14660]  INFO -- :   Rendered home/index.html.erb within layouts/application (5.7ms)
I, [2015-04-24T11:07:39.128187 #14660]  INFO -- : Completed 200 OK in 8ms (Views: 6.5ms | ActiveRecord: 0.5ms)
I, [2015-04-24T11:07:39.297258 #14660]  INFO -- : Started GET "/assets/normalize.css" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.405988 #14660]  INFO -- : Started GET "/assets/jquery.bxslider.css" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.426371 #14660]  INFO -- : Started GET "/assets/index_style.css" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.531393 #14660]  INFO -- : Started GET "/assets/jquery.js?body=1" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.545523 #14637]  INFO -- : Started GET "/assets/turbolinks.js?body=1" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.570849 #14637]  INFO -- : Started GET "/assets/jquerycode.min.js" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.649997 #14637]  INFO -- : Started GET "/assets/jquery_index.min.js" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.660387 #14637]  INFO -- : Started GET "/assets/jquery.bxslider.min.js" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:39.668924 #14637]  INFO -- : Started GET "/assets/jquery_ujs.js?body=1" for 109.55.1.85 at 2015-04-24 11:07:39 +0000
I, [2015-04-24T11:07:40.731657 #14637]  INFO -- : Started GET "/bx_loader.gif" for 109.55.1.85 at 2015-04-24 11:07:40 +0000
F, [2015-04-24T11:07:40.733622 #14637] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/bx_loader.gif"):
  actionpack (4.0.4) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.0.4) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.0.4) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.0.4) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.0.4) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.0.4) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.0.4) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.0.4) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.0.4) lib/active_support/cache/strategy/local_cache.rb:83:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.0.4) lib/rails/engine.rb:511:in `call'
  railties (4.0.4) lib/rails/application.rb:97:in `call'
  passenger (4.0.45) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.45) lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  passenger (4.0.45) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.45) lib/phusion_passenger/request_handler.rb:448:in `block (3 levels) in start_threads'

**Comment by DavideDiCarlo** [comment]
Done on  merge #22  :+1:
